// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HjctZ48Zaf3_mY2ricBiKD_-g5SfQts',
    appId: '1:19307360023:web:575bf216faeec182329152',
    messagingSenderId: '19307360023',
    projectId: 'bloodbridge-690e5',
    authDomain: 'bloodbridge-690e5.firebaseapp.com',
    storageBucket: 'bloodbridge-690e5.appspot.com',
    measurementId: 'G-JQFZX2Y21L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6W22bo0nAx8ipc6qwCEhZY10M0GRmKI',
    appId: '1:19307360023:android:4aab2bf96896452b329152',
    messagingSenderId: '19307360023',
    projectId: 'bloodbridge-690e5',
    storageBucket: 'bloodbridge-690e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12KieiW9AJZ162HxcxGR-muqTBjo5dTQ',
    appId: '1:19307360023:ios:7aa525ae8b659147329152',
    messagingSenderId: '19307360023',
    projectId: 'bloodbridge-690e5',
    storageBucket: 'bloodbridge-690e5.appspot.com',
    iosBundleId: 'com.example.bloodbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12KieiW9AJZ162HxcxGR-muqTBjo5dTQ',
    appId: '1:19307360023:ios:93258992e7858876329152',
    messagingSenderId: '19307360023',
    projectId: 'bloodbridge-690e5',
    storageBucket: 'bloodbridge-690e5.appspot.com',
    iosBundleId: 'com.example.bloodbridge.RunnerTests',
  );
}
